name: Build iOS App - Production Ready

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        npm ci --legacy-peer-deps
        npm install -g @capacitor/cli@latest
        
    - name: Build Production Web App
      run: npm run build
      
    - name: Sync iOS Project
      run: npx cap sync ios
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
        
    - name: Create iOS Build
      env:
        APPLE_TEAM_ID: "82LWX6TABF"
        BUNDLE_ID: "com.commertize.app"
      run: |
        cd ios/App
        
        # List available schemes
        xcodebuild -list
        
        # Build for device (Release configuration)
        xcodebuild \
          -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath "Commertize.xcarchive" \
          archive \
          DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
          PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID"
          
    - name: Export App Store IPA
      run: |
        cd ios/App
        
        # Create export options for App Store
        cat
